"""add set null for post relations

Revision ID: 0b4a2cde623b
Revises: 555e547efe5b
Create Date: 2026-05-24 12:00:19.321405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4a2cde623b'
down_revision: Union[str, Sequence[str], None] = '555e547efe5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blog_post_location_id_fkey'), 'blog_post', type_='foreignkey')
    op.drop_constraint(op.f('blog_post_category_id_fkey'), 'blog_post', type_='foreignkey')
    op.create_foreign_key(None, 'blog_post', 'blog_location', ['location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'blog_post', 'blog_category', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_post', type_='foreignkey')
    op.drop_constraint(None, 'blog_post', type_='foreignkey')
    op.create_foreign_key(op.f('blog_post_category_id_fkey'), 'blog_post', 'blog_category', ['category_id'], ['id'])
    op.create_foreign_key(op.f('blog_post_location_id_fkey'), 'blog_post', 'blog_location', ['location_id'], ['id'])
    # ### end Alembic commands ###
