"""cascade comments

Revision ID: 555e547efe5b
Revises: 8a3e3fed3eef
Create Date: 2026-05-23 18:24:42.883924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555e547efe5b'
down_revision: Union[str, Sequence[str], None] = '8a3e3fed3eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_comment', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_blog_comment_id'), table_name='blog_comment')
    op.drop_constraint(op.f('blog_comment_post_id_fkey'), 'blog_comment', type_='foreignkey')
    op.create_foreign_key(None, 'blog_comment', 'blog_post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_comment', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_comment', type_='foreignkey')
    op.drop_constraint(None, 'blog_comment', type_='foreignkey')
    op.create_foreign_key(op.f('blog_comment_post_id_fkey'), 'blog_comment', 'blog_post', ['post_id'], ['id'])
    op.create_index(op.f('ix_blog_comment_id'), 'blog_comment', ['id'], unique=False)
    op.alter_column('blog_comment', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
